configure_file(input: 'config_types.h.in', output: 'config_types.h',
  configuration: {
    'INCLUDE_INTTYPES_H': 1,
    'INCLUDE_STDINT_H': 1,
    'INCLUDE_SYS_TYPES_H': 1,
    'SIZE16': 'int16_t', 'USIZE16': 'uint16_t',
    'SIZE32': 'int32_t', 'USIZE32': 'uint32_t',
    'SIZE64': 'int64_t', 'USIZE64': 'uint64_t'
  }
)
