# cross file for Linux aarch64 with Zig.
# use this file by running meson setup --cross-file resources/cross/linux-zig-aarch64.ini <builddir>

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[binaries]
c = ['zig', 'cc', '-target', 'aarch64-linux-gnu.2.17.0']
cpp = ['zig', 'c++', '-target', 'aarch64-linux-gnu.2.17.0']
ar = ['sh', '@GLOBAL_SOURCE_ROOT@/scripts/zig-ar.sh']
ranlib = ['zig', 'ranlib']
objcopy = ['zig', 'objcopy']
strip = 'strip'
cmake = 'cmake'
pkg-config = 'pkg-config'

[built-in options]
c_args = ['-isystem', '/usr/include/aarch64-linux-gnu']
cpp_args = ['-isystem', '/usr/include/aarch64-linux-gnu']
