# cross file for Windows x86_64.
# use this file by running meson setup --cross-file resources/cross/linux-mingw32-x86_64.ini <builddir>

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[binaries]
c = 'x86_64-w64-mingw32-gcc'
cpp = 'x86_64-w64-mingw32-g++'
objc = 'x86_64-w64-mingw32-gcc'
ar = 'x86_64-w64-mingw32-ar'
strip = 'x86_64-w64-mingw32-strip'
windres = 'x86_64-w64-mingw32-windres'
exe_wrapper = 'wine'
cmake = 'cmake'

[project options]
buildtype = 'release'
ppm = false
portable = true
wrap_mode = 'forcefallback'
