# cross file for Linux x86_64 with Zig.
# use this file by running meson setup --cross-file resources/cross/linux-zig-x86_64.ini <builddir>

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[binaries]
c = ['zig', 'cc', '-target', 'x86_64-linux-gnu.2.17.0']
cpp = ['zig', 'c++', '-target', 'x86_64-linux-gnu.2.17.0']
ar = ['sh', '@GLOBAL_SOURCE_ROOT@/scripts/zig-ar.sh']
ranlib = ['zig', 'ranlib']
objcopy = ['zig', 'objcopy']
strip = 'strip'
cmake = 'cmake'
pkg-config = 'pkg-config'

[built-in options]
c_args = ['-isystem', '/usr/include/x86_64-linux-gnu']
cpp_args = ['-isystem', '/usr/include/x86_64-linux-gnu']
